version: "3.4"

services:
  mysql:
    container_name: seckill-mysql
    image: mysql:8
    privileged: true
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wh_seckill}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql:/var/lib/mysql/
      - ./sql/wh_seckill.sql:/docker-entrypoint-initdb.d/wh_seckill.sql:ro

  redis:
   container_name: ssadmin-redis
   privileged: true
   image: redis:7-alpine
   restart: unless-stopped
   ports:
     - "6379:6379"
   volumes:
     - redis:/data

  rabbitmq:
    container_name: seckill-rabbitmq
    privileged: true
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:4.0.5-alpine
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./conf:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456

  server:
    container_name: seckill-server
    build:
      context: ./backend/
    image: seckill-server
    privileged: true
    restart: unless-stopped
    ports:
      - "28080:28080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS:
        ${JAVA_OPTS:-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        }
      ARGS:
        --spring.datasource.url=${DATASOURCE_URL:-jdbc:mysql://seckill-mysql:3306/wh_seckill?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.username=${DATASOURCE_USERNAME:-root}
        --spring.datasource.password=${DATASOURCE_PASSWORD:-123456}
        --spring.data.redis.host=${REDIS_HOST:-ssadmin-redis}
        --spring.rabbitmq.host=${RABBITMQ_HOST:-seckill-rabbitmq}
        --spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:-root}
        --spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:-123456}
        --seckill.jwt.admin-secret-key=thedjasfkljfaiorejklafdloierwaahfdajskhkwrqoifdanjrhewjqkhdsnfngkjeurqnfdjka
        --seckill.jwt.admin-token-name=token
    depends_on:
      - mysql
      - redis
      - rabbitmq


  web:
    container_name: seckill-web
    build:
      context: ./frontend/whtrainseckill
      args:
        NODE_ENV:
          ENV=${NODE_ENV:-production}
          VUE_APP_TITLE=${VUE_APP_TITLE:-seckill管理系统}
    image: seckill-web
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  rabbitmq:
    driver: local
